// Mocks generated by Mockito 5.4.5 from annotations
// in liftly/test/features/progression/services/session_progression_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:liftly/common/enums/progression_type_enum.dart' as _i10;
import 'package:liftly/features/exercise/models/exercise.dart' as _i9;
import 'package:liftly/features/progression/models/progression_calculation_result.dart' as _i4;
import 'package:liftly/features/progression/models/progression_config.dart' as _i5;
import 'package:liftly/features/progression/models/progression_state.dart' as _i6;
import 'package:liftly/features/progression/models/progression_template.dart' as _i8;
import 'package:liftly/features/progression/services/progression_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeProgressionService_1 extends _i1.SmartFake implements _i3.ProgressionService {
  _FakeProgressionService_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeProgressionCalculationResult_2 extends _i1.SmartFake implements _i4.ProgressionCalculationResult {
  _FakeProgressionCalculationResult_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeProgressionConfig_3 extends _i1.SmartFake implements _i5.ProgressionConfig {
  _FakeProgressionConfig_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeProgressionState_4 extends _i1.SmartFake implements _i6.ProgressionState {
  _FakeProgressionState_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [ProgressionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressionService extends _i1.Mock implements _i3.ProgressionService {
  MockProgressionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeNotifierProviderRef<_i3.ProgressionService> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeAutoDisposeNotifierProviderRef_0<_i3.ProgressionService>(this, Invocation.getter(#ref)),
          )
          as _i2.AutoDisposeNotifierProviderRef<_i3.ProgressionService>);

  @override
  _i3.ProgressionService get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProgressionService_1(this, Invocation.getter(#state)),
          )
          as _i3.ProgressionService);

  @override
  set state(_i3.ProgressionService? value) =>
      super.noSuchMethod(Invocation.setter(#state, value), returnValueForMissingStub: null);

  @override
  _i3.ProgressionService build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeProgressionService_1(this, Invocation.method(#build, [])),
          )
          as _i3.ProgressionService);

  @override
  _i7.Future<void> saveProgressionConfig(_i5.ProgressionConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgressionConfig, [config]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.ProgressionConfig?> getProgressionConfig(String? configId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressionConfig, [configId]),
            returnValue: _i7.Future<_i5.ProgressionConfig?>.value(),
          )
          as _i7.Future<_i5.ProgressionConfig?>);

  @override
  _i7.Future<_i5.ProgressionConfig?> getActiveProgressionConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveProgressionConfig, []),
            returnValue: _i7.Future<_i5.ProgressionConfig?>.value(),
          )
          as _i7.Future<_i5.ProgressionConfig?>);

  @override
  _i7.Future<List<_i5.ProgressionConfig>> getAllProgressionConfigs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProgressionConfigs, []),
            returnValue: _i7.Future<List<_i5.ProgressionConfig>>.value(<_i5.ProgressionConfig>[]),
          )
          as _i7.Future<List<_i5.ProgressionConfig>>);

  @override
  _i7.Future<void> deleteProgressionConfig(String? configId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgressionConfig, [configId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cleanupInactiveProgressionStates() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupInactiveProgressionStates, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveProgressionState(_i6.ProgressionState? state) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgressionState, [state]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.ProgressionState?> getProgressionState(String? stateId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressionState, [stateId]),
            returnValue: _i7.Future<_i6.ProgressionState?>.value(),
          )
          as _i7.Future<_i6.ProgressionState?>);

  @override
  _i7.Future<_i6.ProgressionState?> getProgressionStateByExercise(
    String? configId,
    String? exerciseId,
    String? routineId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressionStateByExercise, [configId, exerciseId, routineId]),
            returnValue: _i7.Future<_i6.ProgressionState?>.value(),
          )
          as _i7.Future<_i6.ProgressionState?>);

  @override
  _i7.Future<List<_i6.ProgressionState>> getProgressionStatesByConfig(String? configId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressionStatesByConfig, [configId]),
            returnValue: _i7.Future<List<_i6.ProgressionState>>.value(<_i6.ProgressionState>[]),
          )
          as _i7.Future<List<_i6.ProgressionState>>);

  @override
  _i7.Future<void> saveProgressionTemplate(_i8.ProgressionTemplate? template) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgressionTemplate, [template]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.ProgressionTemplate>> getAllProgressionTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProgressionTemplates, []),
            returnValue: _i7.Future<List<_i8.ProgressionTemplate>>.value(<_i8.ProgressionTemplate>[]),
          )
          as _i7.Future<List<_i8.ProgressionTemplate>>);

  @override
  _i7.Future<_i8.ProgressionTemplate?> getProgressionTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressionTemplate, [templateId]),
            returnValue: _i7.Future<_i8.ProgressionTemplate?>.value(),
          )
          as _i7.Future<_i8.ProgressionTemplate?>);

  @override
  _i7.Future<_i4.ProgressionCalculationResult> calculateProgression(
    String? configId,
    String? exerciseId,
    String? routineId,
    double? currentWeight,
    int? currentReps,
    int? currentSets, {
    required _i9.Exercise? exercise,
    bool? isExerciseLocked = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #calculateProgression,
              [configId, exerciseId, routineId, currentWeight, currentReps, currentSets],
              {#exercise: exercise, #isExerciseLocked: isExerciseLocked},
            ),
            returnValue: _i7.Future<_i4.ProgressionCalculationResult>.value(
              _FakeProgressionCalculationResult_2(
                this,
                Invocation.method(
                  #calculateProgression,
                  [configId, exerciseId, routineId, currentWeight, currentReps, currentSets],
                  {#exercise: exercise, #isExerciseLocked: isExerciseLocked},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.ProgressionCalculationResult>);

  @override
  _i7.Future<_i5.ProgressionConfig> initializeProgression({
    required _i10.ProgressionType? type,
    required _i10.ProgressionUnit? unit,
    required _i10.ProgressionTarget? primaryTarget,
    _i10.ProgressionTarget? secondaryTarget,
    required double? incrementValue,
    required int? incrementFrequency,
    required int? cycleLength,
    required int? deloadWeek,
    required double? deloadPercentage,
    Map<String, dynamic>? customParameters,
    bool? isGlobal = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeProgression, [], {
              #type: type,
              #unit: unit,
              #primaryTarget: primaryTarget,
              #secondaryTarget: secondaryTarget,
              #incrementValue: incrementValue,
              #incrementFrequency: incrementFrequency,
              #cycleLength: cycleLength,
              #deloadWeek: deloadWeek,
              #deloadPercentage: deloadPercentage,
              #customParameters: customParameters,
              #isGlobal: isGlobal,
            }),
            returnValue: _i7.Future<_i5.ProgressionConfig>.value(
              _FakeProgressionConfig_3(
                this,
                Invocation.method(#initializeProgression, [], {
                  #type: type,
                  #unit: unit,
                  #primaryTarget: primaryTarget,
                  #secondaryTarget: secondaryTarget,
                  #incrementValue: incrementValue,
                  #incrementFrequency: incrementFrequency,
                  #cycleLength: cycleLength,
                  #deloadWeek: deloadWeek,
                  #deloadPercentage: deloadPercentage,
                  #customParameters: customParameters,
                  #isGlobal: isGlobal,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.ProgressionConfig>);

  @override
  _i7.Future<_i6.ProgressionState> initializeExerciseProgression({
    required String? configId,
    required String? exerciseId,
    required String? routineId,
    required double? baseWeight,
    required int? baseReps,
    required int? baseSets,
    double? oneRepMax,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeExerciseProgression, [], {
              #configId: configId,
              #exerciseId: exerciseId,
              #routineId: routineId,
              #baseWeight: baseWeight,
              #baseReps: baseReps,
              #baseSets: baseSets,
              #oneRepMax: oneRepMax,
            }),
            returnValue: _i7.Future<_i6.ProgressionState>.value(
              _FakeProgressionState_4(
                this,
                Invocation.method(#initializeExerciseProgression, [], {
                  #configId: configId,
                  #exerciseId: exerciseId,
                  #routineId: routineId,
                  #baseWeight: baseWeight,
                  #baseReps: baseReps,
                  #baseSets: baseSets,
                  #oneRepMax: oneRepMax,
                }),
              ),
            ),
          )
          as _i7.Future<_i6.ProgressionState>);

  @override
  void listenSelf(
    void Function(_i3.ProgressionService?, _i3.ProgressionService)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i3.ProgressionService? previous, _i3.ProgressionService? next) =>
      (super.noSuchMethod(Invocation.method(#updateShouldNotify, [previous, next]), returnValue: false) as bool);
}
